comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches: null
coverage:
  status:
    project:
      default:
        target: 75%
    patch:
      default:
        target: 75%
